#!/bin/sh

#cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

#cp \
#    $FOAM_TUTORIALS/resources/geometry/membrane-boundaries.stl.gz \
#    $FOAM_TUTORIALS/resources/geometry/membrane-membrane.stl.gz \
#    constant/triSurface
runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication snappyHexMesh -overwrite
rm -f 0/cellLevel 0/pointLevel

# Remove cells inside the 4 mm nozzle channel (keep top 4 mm only).
# Step 1: select channel cells and build fluidDomain (inverted set)
runApplication -s removeCells topoSet -dict system/topoSetDict.removeCells
# Step 2: keep only fluidDomain cells; exposes cut-plane faces as patch 'nozzleChannel'
#         (removeCells not available in ESI v2406; subsetMesh is the equivalent)
runApplication subsetMesh fluidDomain -overwrite -patch nozzleChannel

runApplication topoSet
runApplication createPatch -overwrite

# Copy initial conditions AFTER mesh is fully finalized so patch names match
cp -r 0.orig/* 0/.

runApplication checkMesh
runApplication renumberMesh -overwrite
runApplication potentialFoam #set initial U field
touch open.foam
#replace the gamma 
#sed -i '38s/gamma           1;/gamma           1.4;/' 0/p
#restore0Dir

#runApplication setFields

#runApplication reactingFoam

#------------------------------------------------------------------------------
